---

  # role: geerlingguy.apache
  apache_listen_port: 80
  apache_vhosts:
    - {servername: "project.dev", documentroot: "/vagrant/project/www/"}
  apache_mods_enabled:
    - rewrite.load

  # role: geerlingguy.php
  php_memory_limit: "128M"
  php_max_execution_time: "90"
  php_upload_max_filesize: "256M"
  # @see: http://packages.ubuntu.com/source/trusty-updates/php5
  php_packages:
    - php5
    - php5-cgi
    - php5-cli
    - php5-common
    - php5-curl
    - php5-dev
    - php5-mysqlnd


  # role: geerlingguy.mysql
  mysql_root_password: rootpassword
  mysql_databases:
    - name: project_dev
  mysql_users:
    - name: project_user
      host: "%"
      password: projectuserpassword
      priv: "project_dev.*:ALL"

