---
- hosts: all

  vars_files:
    - vars/init.yml

  tasks:
    - name: playbook.yml | Hello World!
      shell: /bin/echo "<h1>Hello World! from playbook.yml</h1>" > /vagrant/project/www/index.html

    - name: playbook.yml | PHP Info
      shell: /bin/echo "<?php phpinfo(); ?>" > /vagrant/project/www/info.php

    - name: playbook.yml | Install Apache libapache2-mod-php5
      apt: pkg=libapache2-mod-php5 state=installed update_cache=true

  roles:
    - { role: geerlingguy.apache }
    - { role: geerlingguy.mysql }
    - { role: geerlingguy.php }
