---
- hosts: all
  vars_files:
    - vars/init.yml
  tasks:
    - name: Hello World!
      shell: /bin/echo "Hello World!" > /vagrant/hello.txt
  roles:
    - { role: geerlingguy.apache }
#    - { role: geerlingguy.mysql }
    - { role: geerlingguy.php }
